export default function Head() {
  return (
    <>
      <title>My TODO list</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/27b9e386375ebde43a9b022ba6c9d727.png" />
    </>
  );
}
